sudo: required

services:
  - docker

before_install:
  - docker build -t aontimer/Mxonline3 .
  - echo "jmdjsj903291A" | docker login -u "aontimer" --password-stdin
  - docker push aontimer/Mxonline3
